{{ generated_header }}
{% if base_os == "rhel7" %}
FROM rhel7:latest
{% elif base_os == "centos7" %}
FROM centos:centos7
{% endif %}

# Pause indefinitely if asked to do so.
RUN test "$OO_PAUSE_ON_BUILD" = "true" && while sleep 10; do true; done || :

{% if base_os == "rhel7" %}
# setup yum repos
ADD setup-yum.sh /usr/local/bin/setup-yum.sh
RUN /usr/local/bin/setup-yum.sh
RUN yum repolist --disablerepo=* && \
    yum-config-manager --disable \* > /dev/null && \
    yum-config-manager --enable rhel-7-server-rpms rhel-7-server-extras-rpms
{% elif base_os == "centos7" %}

ADD copr-openshift-tools.repo /etc/yum.repos.d/
{% endif %}

# creature comforts (make it feel like a normal linux environment)
ENV LANG en_US.UTF-8
ENV CONTAINER docker
ENV USER root
ENV HOME /root
ENV TERM xterm
WORKDIR /root
ADD root/bashrc /root/.bashrc
ADD root/pdbrc /root/.pdbrc

# Make working in Python nice
ADD root/pythonrc /root/.pythonrc
ENV PYTHONSTARTUP=/root/.pythonrc

# setup epel repo
RUN rpm -ivh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

RUN yum clean metadata && \
    yum -y update && \
    yum -y install iputils cronie ansible vim procps less ack tar psmisc python-scandir lsof && \
    yum clean all

# Setup locales.  It comes broken (probably a size issue) by default in the docker image.
RUN yum -y reinstall glibc-common &&  \
    yum clean all  && \
    mv -f /usr/lib/locale/locale-archive /usr/lib/locale/locale-archive.tmpl  && \
    /usr/sbin/build-locale-archive

# Setup Cron
ADD pamd.crond /etc/pam.d/crond

# Setup Ansible
ADD ansible.cfg /etc/ansible/ansible.cfg
RUN echo -e '[local]\nlocalhost       ansible_connection=local\n' > /etc/ansible/hosts

# Make the container work more consistently in and out of openshift
# BE CAREFUL!!! If you change these, you may bloat the image! Use 'docker history' to see the size!
RUN chmod -R g+rwX /root/
