= simpleSAMLphp SSO application Docker container

This docker container provides an HTTP endpoint and an SSH endpoint
for single sign-on (SSO) to a SAML2 identity provider (IdP). The SSO
can be used to authenticate to configured SAML2-enabled service
providers (SPs).

== Setup

See https://github.com/openshift/openshift-tools/blob/prod/docker/README.adoc#setup[general setup].

Nothing additional needs to be setup for this container.

== Build

To build this container, simply execute the build script.

.Example:
[source,bash]
----
./[rhel7|centos7]/build.sh
----

== Run

To run this container, simply execute the run script.

.Example:
[source,bash]
----
./[rhel7|centos7]/run.sh
----

== Maintain

Inside of `saml20-sp-remote.php.j2` is an Amazon signed certificate for `Subject: CN=urn:amazon:webservices, O=Amazon Web Services, Inc., ST=Washington, C=US` with a one year lifetime.

This certificate will expire yearly, on or around August 1st.

Before this happens, gather the information from https://signin.aws.amazon.com/static/saml-metadata.xml and cut/paste the x509 cert into the j2 template.

Remember to generate the rhel/centos images with generate-containers.yml before creating your PR.

NOTE: This step needs to be automated, such that the pod can retrieve the updates automatically whenever it detects the notAfter date is approaching.


