#!/bin/env python

# Copyright 2015 Red Hat Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: Jesse Kennedy <jessek@redhat.com>

"""Plots a bar chart from aggregated event occurences"""

def main():
    """main"""
    import argparse
    from openshift_tools.reporting.zabbixplot import ZabbixPlot

    parser = argparse.ArgumentParser(description='Plots a bar chart from aggregated event occurences')

    parser.add_argument('-s', '--server', required=True, help='url of the Zabbix host (http://host/path/)')
    parser.add_argument('-u', '--username', required=True, help='username')
    parser.add_argument('-p', '--password', required=True, help='password')
    parser.add_argument('-g', '--group', required=True, help='host group name')
    parser.add_argument('-t', '--trigger', required=True,
                        help='trigger description (variables in the description will not be filled in)')
    parser.add_argument('-d', '--days', default=7, type=int, help='days of data to retrieve (default: 7)')
    parser.add_argument('-n', '--num-hosts', type=int, help='number of hosts contained in host group. the default is '
                        'the number of hosts seen in the returned data, but this number will exclude hosts with no'
                        'events.')
    parser.add_argument('-c', '--periods', type=int, help='number of periods to display (default: number of days)')
    parser.add_argument('-l', '--limit', default=25000, type=int, help='maximum number of events to fetch '
                        '(default: 25000)')

    args = parser.parse_args()

    plot = ZabbixPlot(
        server=args.server,
        username=args.username,
        password=args.password,
        group=args.group,
        trigger=args.trigger,
        days=args.days,
        limit=args.limit
    )

    plot.plot_aggregate(args.periods, args.num_hosts)

if __name__ == "__main__":
    main()
