#!/bin/bash

# This is a temporary script until we get cron running as non-root (or find something else)

if [ $# -lt 2 ] ; then
    echo "Usage: $(basename $0) <sleep_time> <command>"
    exit 1
fi

SLEEP_TIME=$1
shift
COMMAND=$@

# The purpose of this script is to run something in an infinite loop
while true ; do
    eval $COMMAND
    sleep $SLEEP_TIME
done
