#!/bin/bash
if [[ $@ = "member list" ]];
then
    /usr/bin/etcdctl --ca-file /etc/etcd/ca.crt  --cert-file /etc/etcd/peer.crt --key-file /etc/etcd/peer.key --endpoints https://$(hostname):2379 ${@}
else
    ETCDCTL_API=3 /usr/bin/etcdctl --cert /etc/etcd/peer.crt --key /etc/etcd/peer.key --cacert /etc/etcd/ca.crt --endpoints https://$(hostname):2379 ${@}
fi
