{{ generated_header }}
# Example docker run command
# docker run -ti --net=host --name web --rm=true oso-{{ base_os }}-clamd

{% if base_os == "rhel7" %}
FROM oso-rhel7-ops-clambase:latest
{% elif base_os == "centos7" %}
FROM openshifttools/oso-centos7-ops-clambase:latest
{% endif %}

# Pause indefinitely if asked to do so.
ARG OO_PAUSE_ON_BUILD
RUN test "$OO_PAUSE_ON_BUILD" = "true" && while sleep 10; do true; done || :

# Install clamd
RUN yum-install-check.sh -y \
        clamav-server \
        && \
    yum -y update && yum clean all

# Start clamd
CMD /usr/sbin/clamd

ADD clamd.conf /etc/

# Fix v3 specific environment
# Make the container work more consistently in and out of openshift
# BE CAREFUL!!! If you change these, you may bloat the image! Use 'docker history' to see the size!
RUN mkdir -p /var/log/clamav && \
    touch /var/log/clamav/clamd.log && \
    chmod -R g+rwX /var/run /var/log && \
    chgrp -R root /var/run/ /var/log && \
    echo clam:x:10000:0:USER:/root:/bin/bash >> /etc/passwd
#    ansible-playbook /root/build.yaml && \
#    rm -rf /root/.ansible
