{{ generated_header }}
# Example docker run command
# docker run -ti --net=host --name web --rm=true oso-{{ base_os }}-saml-sso
# /root/start.sh will then start the httpd.

{% if base_os == "rhel7" %}
FROM oso-rhel7-ops-base:latest
{% elif base_os == "centos7" %}
FROM openshifttools/oso-centos7-ops-base:latest
{% endif %}

# Pause indefinitely if asked to do so.
RUN test "$OO_PAUSE_ON_BUILD" = "true" && while true ; do sleep 10 ; done || :

EXPOSE 8443

ADD install_simplesaml.sh start.sh /usr/local/bin/

# Install zabbix from zabbix repo
# Also, install simplesaml via our install script and then remove the script
RUN yum install -y \
        httpd \
        lsof \
        mod_ssl \
        openssh-server \
        php php-cli \
        php-google-apiclient \
        php-pecl-memcache \
        php-pecl-yaml \
        wget \
        && \
    yum -y update && yum clean all && \
    install_simplesaml.sh && \
    rm -f /usr/local/bin/install_simplesaml.sh


# Install our custom authentication module and authorization module
ADD simplesamlphp/modules/authgoogle/ /usr/share/simplesamlphp/modules/authgoogle/
ADD simplesamlphp/modules/authorizeyaml/ /usr/share/simplesamlphp/modules/authorizeyaml/
ADD simplesamlphp/modules/themeoso/ /usr/share/simplesamlphp/modules/themeoso/
RUN ln -sf /usr/share/simplesamlphp/modules/authorizeyaml/bin/get_saml_token.php /usr/local/bin/get_saml_token

# Copy config files
ADD httpd.conf /etc/httpd/conf/
ADD sshd_config /etc/ssh/sshd_config

# Copy index redirect page and readyness/liveness probe handler
ADD index.php status.php /var/www/html/

# Start apache & sshd
CMD /usr/local/bin/start.sh

# Add config file templates and startup playbook
ADD root/ /root/

# Fix v3 specific environment
# Make the container work more consistently in and out of openshift
# Also, set the timezone in the php.ini file and
# do RHEL7.2 Fix for mod_auth_digest writing to /run/httpd/authdigest_shm.pid
# BE CAREFUL!!! If you change these, you may bloat the image! Use 'docker history' to see the size!
RUN mkdir -p /run/httpd && \
    chmod -R g+rwX /etc/httpd /etc/passwd /etc/group /run /var/log /usr/share/simplesamlphp/config && \
    chgrp -R root /run/ /var/log /var/lib/php/session && \
    sed -r -ie 's/^;(date.timezone).*/\1 = America\/New_York/g' /etc/php.ini && \
    sed -i -e 's/^\(LoadModule auth_digest_module modules\/mod_auth_digest.so\)$/#\1/g' /etc/httpd/conf.modules.d/00-base.conf
