#!/usr/bin/ansible-playbook
---
- hosts: localhost
  gather_facts: true

  pre_tasks:
  - name: Checking build environment
    fail:
      msg: "Unsupported build environment"
    when: (ansible_distribution == "RedHat" and ansible_distribution_major_version < 7) or 
          (ansible_distribution == "CentOS" and ansible_distribution_major_version < 7) or
          (ansible_distribution == "Fedora" and ansible_distribution_major_version < 22) or
          (ansible_distribution != "RedHat" and ansible_distribution != "Fedora" and ansible_distribution != "CentOS")

  roles:
  - role: "generate_containers"
    base_os: rhel7

  - role: "generate_containers"
    base_os: centos7
