# openshift-tools RPM Build instructions
This repository uses tito to make building and tracking revisions easy.

For more information on tito, please see the http://rm-rf.ca/tito[Tito home page]


## Build python-openshift-tools-* RPMs
. Change into openshift-tools/openshift_tools directory
+
----
cd openshift-tools/openshift_tools
----
+
. Get the latest code
+
----
git pull
----
. Get the latest tags
+
----
git fetch --tags
----
+
. Build test packages (no tagging needed)
+
----
tito build --test --rpm
----
+
. OPTIONAL: If a new version of the package is needed, follow these instructions:
.. Tag a new build (bumps version number and adds log entries)
+
----
# Something like this (copy it from the tito output):
git push && git push origin package-name-and-new-VERSION
----
+
----
tito tag
----
+
.. Follow the on screen tito instructions to push the tags
. Build new packages based on the latest tag information
+
----
tito build --rpm
----

## Build openshift-tools-web-* RPMs
. Change into openshift-tools/web directory
+
----
cd openshift-tools/web
----
+
. Get the latest code
+
----
git pull
----
. Get the latest tags
+
----
git fetch --tags
----
+
. Build test packages (no tagging needed)
+
----
tito build --test --rpm
----
+
. OPTIONAL: If a new version of the package is needed, follow these instructions:
.. Tag a new build (bumps version number and adds log entries)
+
----
tito tag
----
+
.. Follow the on screen tito instructions to push the tags
+
----
# Something like this (copy it from the tito output):
git push && git push origin package-name-and-new-VERSION
----
. Build new packages based on the latest tag information
+
----
tito build --rpm
----
