# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias vi=vim

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Set the prompt to the container id
# We explicitly do this so that it looks like a container even with:
#   --net=host
#   --net=container
# Both of these docker run options give confusing bash prompts inside the container.
export container_uuid=$(cat /proc/self/cgroup | grep -o -e "docker-.*.scope" | head -n1 | sed -e "s/docker-\(.*\)\.scope/\\1/" | cut -c1-12)
export PS1="[CTR][\u@$container_uuid \W]\$ "
