#!/usr/bin/env python
#
# enable syntax completion
'''
Add auto-completion and a stored history file of commands to your Python
interactive interpreter. Requires Python 2.0+, readline. Autocomplete is
bound to the Esc key by default (you can change it - see readline docs).

Store the file in ~/.pystartup, and set an environment variable to point
to it:  "export PYTHONSTARTUP=~/.pystartup" in bash.
'''
try:
    import readline
except ImportError:
    print "Module readline not available."
else:
    import rlcompleter
    readline.parse_and_bind("tab: complete")

# Add auto-completion and a stored history file of commands to your Python
# interactive interpreter. Requires Python 2.0+, readline. Autocomplete is
# bound to the Esc key by default (you can change it - see readline docs).
#
# Store the file in ~/.pystartup, and set an environment variable to point
# to it:  "export PYTHONSTARTUP=~/.pystartup" in bash.

import atexit
import os
import readline
import rlcompleter

HISTORYPATH = os.path.expanduser("~/.pyhistory")

def save_history(history_path=HISTORYPATH):
    ''' save history to file on exit '''
    readline.write_history_file(history_path)

if os.path.exists(HISTORYPATH):
    readline.read_history_file(HISTORYPATH)

atexit.register(save_history)
del os, atexit, readline, rlcompleter, save_history, HISTORYPATH
